# The title of your site
title: nosykitty

author:
  name: nosykitty
# comment the following line to use your github avatar:
  avatar: "https://www.nautiljon.com/images/perso/00/53/shizuku_9835.jpg"

# Put here the url to your site (e.g. url: https://username.github.io and baseurl: /ask)
url: http://kiutsu.tk
baseurl: /ask

# Customization
custom:
  accent: "pink"
  prompt: "Pose moi une question !!!"
  followup_prompt: "Answer with another question?"
  

# Localization
lang: fr

# Configuration stuff you don't care about
plugins:
  - jekyll-paginate
  - jemoji
permalink: pretty
success_path: /success
paginate: 20
